name: Build and Publish

on: [push]

jobs:

  build-test-staticcheck:
    name: Build, Test and Check
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Restore Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/go/pkg
        key: 1.19-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

    - name: Get go-james
      run: |
        go install github.com/pieterclaerhout/go-james/cmd/go-james

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go-james build

    - name: Test
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go-james test

    - name: Staticcheck
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go-james staticcheck

    - name: Package
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go-james package

    - uses: actions/upload-artifact@v2
      name: Publish
      with:
        name: ${{ env.GITHUB_REPOSITORY_NAME }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_NAME }}.zip
        path: build/*.*
